# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    branches-ignore:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies
        run: npm ci
        
      - name: npm audit action
        uses: oke-py/npm-audit-action@v1.7.2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: gustavofabro
          issue_labels: vulnerability,test
          dedupe_issues: true
